"""add_image_url

Revision ID: e3b13640c15f
Revises: a92f7922a314
Create Date: 2026-05-15 13:34:44.529223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b13640c15f'
down_revision: Union[str, None] = 'a92f7922a314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('news', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image_url')
    op.drop_column('events', 'image_url')
    # ### end Alembic commands ###
